#!/bin/bash

create_env_file() {
    read -p "Silakan masukkan nama env yang ingin dibuat, contoh: robot.env: " name_env
    touch "$name_env"

    declare -a env_variables=("API_ID" "API_HASH" "BOT_TOKEN" "BOT_NAME" "DEV_NAME")
    for var in "${env_variables[@]}"; do
        read -p "Masukkan $var: " value
        echo "$var=$value" >> "$name_env"
    done

    read -p "Apakah file env sudah diisi dengan konfigurasi yang benar? (y/n): " env_configured
    if [ "$env_configured" != "y" ]; then
        rm "$name_env"
        create_env_file
    else
        echo "$name_env telah dibuat."
        read -p "Apakah Anda ingin menjalankan env yang baru dibuat? (y/n): " run_new_env
        if [ "$run_new_env" == "y" ]; then
            git pull && rm -rf *.session* && python3 chatbot.py "$name_env"
            exit 0
        fi
    fi
}

env_files=$(find . -maxdepth 1 -type f -name "*.env" -exec basename {} \;)
if [ -z "$env_files" ]; then
    read -p "Tidak ditemukan file env. Apakah Anda ingin membuatnya sekarang? (y/n): " create_env
    if [ "$create_env" == "y" ]; then
        create_env_file
    else
        echo "Terima kasih. Silakan buat file env kemudian jalankan skrip ini kembali."
        exit 0
    fi
fi

env_files=$(find . -maxdepth 1 -type f -name "*.env" -exec basename {} \;)
echo "Daftar file env yang ditemukan:"
for x in $env_files; do
    echo "$x"
done

while true; do
    read -p "Silakan masukkan nama env yang ingin digunakan: " FILE_ENV

    if [[ ! " $env_files " =~ " $FILE_ENV " ]]; then
        echo "File $FILE_ENV tidak ditemukan. Silakan masukkan nama file yang valid."
    else
        break
    fi
done

git pull && rm -rf *.session* && python3 chatbot.py "$FILE_ENV"
